### ISSUE TITLE
Too large

### ISSUE THREAD

**Issue by tuloski** [xrpsymbol/xrpsymbol.github.io#19]
The symbol is too large and I think there is an ISO standard for that. Maybe with the droplet on the top left corner is better and more balanced?
And each symbol (see USD, EUR, CNY, JPY) have bars or lines crossing so I think this will need it too ;)

**Comment by xrpsymbol** [comment]
The symbol should be converted into a glyph that meets all of the acceptable criteria of the Unicode Standard.
